# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-15 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Employee_ID')),
                ('employee_name', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Employee_Name')),
                ('id', models.IntegerField(blank=True, null=True, verbose_name='ID')),
            ],
            options={
                'ordering': ['id', 'employee_id', 'employee_name'],
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('employee_addr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Employee_Addr.')),
                ('employee_mobile_number', models.IntegerField(blank=True, null=True, verbose_name='Employee_contact_No.')),
                ('employee_designation', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Post')),
                ('employee_city', models.CharField(blank=True, max_length=500, null=True, verbose_name='City')),
                ('employee_blood_grp', models.CharField(blank=True, db_column='employee_Blood_grp', max_length=200, null=True, verbose_name='Blood Group')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['employee', 'employee_addr', 'employee_designation', 'employee_mobile_number', 'employee_city', 'doj', 'employee_blood_grp'],
                'db_table': 'employee_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('employee_salary_monthly', models.CharField(blank=True, db_column='employee_salary_Monthly', max_length=20000, null=True, verbose_name='Salary(per month)')),
                ('doj', models.CharField(db_column='DOJ', max_length=200, primary_key=True, serialize=False, verbose_name='Date of joining')),
                ('id', models.IntegerField(blank=True, null=True, verbose_name='ID')),
            ],
            options={
                'ordering': ['employee_salary_monthly', 'doj'],
                'db_table': 'employee_salary',
                'managed': False,
            },
        ),
    ]
