# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixMovies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(db_column='Movie_name', max_length=500)),
                ('airdate', models.CharField(blank=True, db_column='Airdate', max_length=10, null=True)),
                ('rating', models.CharField(blank=True, db_column='Rating', max_length=10, null=True)),
                ('duration', models.CharField(blank=True, db_column='Duration', max_length=10, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=3000, null=True)),
                ('production_country', models.CharField(blank=True, db_column='Production_country', max_length=1000, null=True)),
                ('added_to_netflix', models.CharField(blank=True, db_column='Added_to_netflix', max_length=100, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=100, null=True)),
                ('movie_url', models.CharField(blank=True, db_column='Movie_url', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'netflix_movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetflixMoviesCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_name', models.CharField(blank=True, max_length=500, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_credits', to='Api_create.NetflixMovies')),
            ],
        ),
    ]
