# Generated by Django 3.0 on 2020-07-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HbogoPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('show_type', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('series_launch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('series_url', models.CharField(blank=True, max_length=255, null=True)),
                ('series_title', models.CharField(blank=True, max_length=255, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('maturity_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_quality', models.CharField(blank=True, max_length=255, null=True)),
                ('video_quality', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('cast', models.TextField(blank=True, null=True)),
                ('producers', models.TextField(blank=True, null=True)),
                ('directors', models.TextField(blank=True, null=True)),
                ('writers', models.TextField(blank=True, null=True)),
                ('expired', models.IntegerField(blank=True, null=True)),
                ('season_count', models.IntegerField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hbogo_programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowtimePrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_program_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('item_type', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=2048, null=True)),
                ('img_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('screen_writers', models.TextField(blank=True, null=True)),
                ('directors', models.TextField(blank=True, null=True)),
                ('story_writers', models.TextField(blank=True, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=128, null=True)),
                ('run_time', models.IntegerField(blank=True, null=True)),
                ('season_cnt', models.IntegerField(blank=True, null=True)),
                ('total_episodes', models.IntegerField(blank=True, null=True)),
                ('series_id', models.IntegerField(blank=True, null=True)),
                ('season_number', models.BigIntegerField(blank=True, null=True)),
                ('episode_number', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('expired', models.IntegerField(blank=True, null=True)),
                ('mapped', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'showtime_programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StarzPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('episode_title', models.CharField(blank=True, max_length=128, null=True)),
                ('new_content', models.IntegerField(blank=True, null=True)),
                ('source_program_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('episode_number', models.BigIntegerField(blank=True, null=True)),
                ('media_id', models.CharField(blank=True, max_length=128, null=True)),
                ('mpaa_rating', models.CharField(blank=True, max_length=8, null=True)),
                ('run_time', models.IntegerField(blank=True, null=True)),
                ('release_year', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('directors', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('popularity', models.BigIntegerField(blank=True, null=True)),
                ('season_id', models.BigIntegerField(blank=True, null=True)),
                ('season_number', models.BigIntegerField(blank=True, null=True)),
                ('is_original', models.IntegerField(blank=True, null=True)),
                ('original_airdate', models.DateTimeField(blank=True, null=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('series_id', models.CharField(blank=True, max_length=32, null=True)),
                ('program_id', models.CharField(blank=True, max_length=32, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'starz_programs',
                'managed': False,
            },
        ),
    ]
