# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Email_id', models.CharField(max_length=20)),
                ('Message', models.CharField(max_length=200)),
            ],
        ),
    ]
