# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_person_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_details',
            old_name='id',
            new_name='ids',
        ),
    ]
