# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20190511_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_details',
            name='Mob_No',
            field=models.IntegerField(default=898198211, max_length=20),
            preserve_default=False,
        ),
    ]
