# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_person_details_mob_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_details',
            name='Mob_No',
            field=models.IntegerField(),
        ),
    ]
