# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20190519_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='persondetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, unique=True)),
                ('lastname', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='person_details',
        ),
    ]
