# Generated by Django 3.0 on 2020-07-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HbogoPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('show_type', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('series_launch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('series_url', models.CharField(blank=True, max_length=255, null=True)),
                ('series_title', models.CharField(blank=True, max_length=255, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('maturity_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_quality', models.CharField(blank=True, max_length=255, null=True)),
                ('video_quality', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('cast', models.TextField(blank=True, null=True)),
                ('producers', models.TextField(blank=True, null=True)),
                ('directors', models.TextField(blank=True, null=True)),
                ('writers', models.TextField(blank=True, null=True)),
                ('expired', models.IntegerField(blank=True, null=True)),
                ('season_count', models.IntegerField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hbogo_programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowtimePrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_program_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('item_type', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=2048, null=True)),
                ('img_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('screen_writers', models.TextField(blank=True, null=True)),
                ('directors', models.TextField(blank=True, null=True)),
                ('story_writers', models.TextField(blank=True, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=128, null=True)),
                ('run_time', models.IntegerField(blank=True, null=True)),
                ('season_cnt', models.IntegerField(blank=True, null=True)),
                ('total_episodes', models.IntegerField(blank=True, null=True)),
                ('series_id', models.IntegerField(blank=True, null=True)),
                ('season_number', models.BigIntegerField(blank=True, null=True)),
                ('episode_number', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('expired', models.IntegerField(blank=True, null=True)),
                ('mapped', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'showtime_programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StarzPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('episode_title', models.CharField(blank=True, max_length=128, null=True)),
                ('new_content', models.IntegerField(blank=True, null=True)),
                ('source_program_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('episode_number', models.BigIntegerField(blank=True, null=True)),
                ('media_id', models.CharField(blank=True, max_length=128, null=True)),
                ('mpaa_rating', models.CharField(blank=True, max_length=8, null=True)),
                ('run_time', models.IntegerField(blank=True, null=True)),
                ('release_year', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('directors', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('popularity', models.BigIntegerField(blank=True, null=True)),
                ('season_id', models.BigIntegerField(blank=True, null=True)),
                ('season_number', models.BigIntegerField(blank=True, null=True)),
                ('is_original', models.IntegerField(blank=True, null=True)),
                ('original_airdate', models.DateTimeField(blank=True, null=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('series_id', models.CharField(blank=True, max_length=32, null=True)),
                ('program_id', models.CharField(blank=True, max_length=32, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'starz_programs',
                'managed': False,
            },
        ),
    ]
