# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190310_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='web_movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=25)),
                ('movie_description', models.CharField(max_length=25000)),
                ('release_year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='movies',
        ),
    ]
