# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190310_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Series',
            },
        ),
        migrations.DeleteModel(
            name='web_movies',
        ),
    ]
