# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-23 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190316_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('movies_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Movies',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
