# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-23 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190323_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('episode_id', models.AutoField(db_column='Episode_Id', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('episode_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('show_id', models.IntegerField(blank=True, null=True)),
                ('content_id', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('airdate', models.CharField(blank=True, max_length=500, null=True)),
                ('season_number', models.CharField(blank=True, max_length=10, null=True)),
                ('episode_number', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('image_url', models.CharField(blank=True, max_length=4000, null=True)),
                ('url', models.CharField(blank=True, max_length=4000, null=True)),
                ('status_field', models.CharField(blank=True, db_column='status_', max_length=100, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=500, null=True)),
                ('is_paid_content', models.CharField(blank=True, max_length=100, null=True)),
                ('isusersubscriber', models.CharField(blank=True, db_column='isUserSubscriber', max_length=100, null=True)),
                ('alternate_title', models.CharField(blank=True, max_length=500, null=True)),
                ('datatracking', models.CharField(blank=True, db_column='dataTracking', max_length=2000, null=True)),
                ('episodes_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('rating', models.CharField(blank=True, max_length=500, null=True)),
                ('is_live', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Episodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('show_id', models.AutoField(primary_key=True)),
                ('show_name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('show_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('availability', models.CharField(blank=True, max_length=500, null=True)),
                ('show_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Series',
                'managed': False,
            },
        ),
    ]
