# Generated by Django 3.0 on 2020-08-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCommontable',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=30)),
                ('season_id', models.CharField(max_length=80)),
                ('series_id', models.CharField(max_length=80)),
                ('parent_id', models.CharField(max_length=100)),
                ('history_ids', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=512)),
                ('episode_title', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('episode_number', models.CharField(blank=True, max_length=11, null=True)),
                ('season_number', models.CharField(blank=True, max_length=11, null=True)),
                ('release_year', models.CharField(blank=True, max_length=4, null=True)),
                ('release_date', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('maturity_ratings', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('is_prime', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_info', models.TextField(blank=True, null=True)),
                ('addon_service', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('directors', models.TextField(blank=True, null=True)),
                ('producers', models.TextField(blank=True, null=True)),
                ('writers', models.TextField(blank=True, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('is_valid', models.IntegerField()),
                ('aux_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_commontable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('source_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=50)),
                ('categories', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MissedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('crawl_status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'missed_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MissedContentInfo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=100)),
                ('item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'missed_content_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('source_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('feed', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=30)),
                ('reference_url', models.TextField(blank=True, null=True)),
                ('count', models.CharField(max_length=100)),
                ('list', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('is_released', models.IntegerField(blank=True, null=True)),
                ('image_url', models.TextField()),
                ('reference_url', models.TextField()),
                ('content_type', models.CharField(max_length=100)),
                ('crawl_frequency', models.IntegerField()),
                ('fas_required', models.IntegerField(blank=True, null=True)),
                ('db_ip', models.CharField(max_length=20)),
                ('db_name', models.CharField(max_length=32)),
                ('proxy_ip', models.CharField(max_length=20)),
                ('proxy_port', models.CharField(max_length=10)),
                ('is_robots', models.IntegerField()),
                ('station_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
    ]
